repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=5000']
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: mixed-line-ending
    -   id: check-merge-conflict
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
        args: ["-l", "120", "--target-version", "py311"]
-   repo: local
    hooks:
    -   id: check-x
        name: Check X
        entry: convertNotebooks.sh
        language: script
        files: ^Examples/
        types: [file, "jupyter"]
