repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=5000']
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: mixed-line-ending
    -   id: check-merge-conflict
-   repo: local
    hooks:
    -   id: check-x
        name: Check X
        entry: convertNotebooks.sh
        language: script
        files: ^Content/
        types: [file, "jupyter"]
